# ============================================
# Main Configuration for PoE Trading Suite
# ============================================

# --- Core Settings ---
# The default league to analyze if none is specified.
default_league: "Mercenaries"

# --- Analysis Configuration ---
analysis:
  # Used for PPH estimations. Assumes a quick buy/vendor/sell cycle.
  assumed_flips_per_hour: 120
  # Thresholds (in Chaos) for assigning risk profiles based on profit standard deviation.
  profit_volatility_risk_thresholds:
    Low: 15
    Medium: 50
    High: 150
    Extreme: 500
  # How many chaos above the minimum price to include an item in a shopping list.
  shopping_list_price_tolerance_chaos: 2.0
  # How many top results to show in detailed breakdowns (e.g., top 5 jackpots).
  num_jackpots_to_display: 5

# --- API & Caching Configuration ---
api:
  base_url: "https://poe.ninja/api/data/"
  trade_url_base: "https://www.pathofexile.com/trade/exchange/"
  # Items to completely exclude from all analyses.
  item_blacklist:
    - "Vaal Gem"
    - "Awakened Support Gem"
    - "Exceptional Gem"
    - "Portal"
    - "Detonate Mines"
    - "Brand Recall"
  # Minimum number of listings for an item to be considered liquid (for currency/fragments).
  minimum_listings: 10

# --- Strategy-Specific Configuration ---
# --- Logging Configuration ---
logging:
  # Global logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Log format string
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # Date format for timestamps
  date_format: "%Y-%m-%d %H:%M:%S"
  # Log file configuration
  file:
    enabled: true
    path: "logs/poe_trading.log"
    max_size_mb: 10
    backup_count: 5
    level: "DEBUG"
  # Console logging configuration
  console:
    enabled: true
    level: "INFO"
    # Whether to use colored output (if colorlog is available)
    colored: true
  # Module-specific log levels
  modules:
    poe_trade_lib.api: "DEBUG"
    poe_trade_lib.strategies: "DEBUG"
    poe_trade_lib.db_utils: "INFO"

strategies:
  gem_corruption:
    # Probabilities for Vaal Orb outcomes on a gem.
    probabilities:
      no_change: 0.25
      level_change: 0.25 # This is split 50/50 between +1 and -1
      quality_change: 0.25
      vaal_version: 0.25
