name: Run PoE Analysis and Log Results

on:
  workflow_dispatch: # Allows you to run the job manually from the GitHub UI
  schedule:
    # Runs at 30 minutes past the hour, every hour
    - cron: '30 * * * *'

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the logging script
        run: python -m apps.log_results

      - name: Get current date
        id: date
        run: echo "date=$(date --iso-8601=seconds)" >> $GITHUB_ENV

      - name: Commit and push database changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update trade database [${{ env.date }}]"
          file_pattern: 'data/historical_trades.db'
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
